"""TRACERA errors package."""

from tracera.errors.exceptions import (
    AgentError,
    CommandExecutionError,
    CommandNotAllowedError,
    ConfigError,
    FileSizeLimitError,
    FileNotFoundInWorkspaceError,
    GitError,
    MaxIterationsError,
    MaxToolCallsError,
    MemoryError,
    MissingAPIKeyError,
    NotAGitRepositoryError,
    PathTraversalError,
    PlanningError,
    ProviderAuthError,
    ProviderContextLengthError,
    ProviderError,
    ProviderNotFoundError,
    ProviderRateLimitError,
    ProviderUnavailableError,
    ToolError,
    ToolNotFoundError,
    ToolValidationError,
    TracerError,
    WorkspaceError,
)

__all__ = [
    "TracerError",
    "ConfigError",
    "MissingAPIKeyError",
    "WorkspaceError",
    "PathTraversalError",
    "FileNotFoundInWorkspaceError",
    "FileSizeLimitError",
    "GitError",
    "NotAGitRepositoryError",
    "ProviderError",
    "ProviderNotFoundError",
    "ProviderRateLimitError",
    "ProviderAuthError",
    "ProviderContextLengthError",
    "ProviderUnavailableError",
    "ToolError",
    "ToolNotFoundError",
    "ToolValidationError",
    "CommandExecutionError",
    "CommandNotAllowedError",
    "AgentError",
    "MaxIterationsError",
    "MaxToolCallsError",
    "PlanningError",
    "MemoryError",
]
